image: node:10.15.1

pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install
          - npx vue-cli-service build --mode staging
        artifacts:
          - dist/**
    - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.4
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "eu-west-1"
              S3_BUCKET: "peek-ui-demo-vadim"
              ACL: "public-read"
              LOCAL_PATH: "dist"
